[workspace]
authors = ["shi_jie <1592277253@qq.com>"]
channels = ["conda-forge"]
name = "Gen4D"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"


[tasks]
pytest = "pytest"

[dependencies]
pytorch-gpu = "*"
tqdm = ">=4.67.1,<5"
torchio = ">=0.20.22,<0.21"
nibabel = ">=5.3.2,<6"
monai = ">=1.5.1,<2"
tifffile = ">=2025.9.20,<2026"
cupy = ">=13.6.0,<14"
einops = ">=0.8.1,<0.9"
imageio = ">=2.37.0,<3"
jsonargparse = ">=4.40.2,<5"
pip = "*"
notebook = "*"
pytest = "*"


[pypi-dependencies]
generate_4d_heart = { path = ".", editable = true }
torchcpd = { git = "https://github.com/BloomingStone/CPD-Pytorch.git", rev = "28ad5b70390ebee6caf5162d1acff70d2cacb66c" }
opencv-python-headless = ">=4.11.0.86, <5"
diffdrr = ">=0.5.1, <0.6"
pyacvd = ">=0.3.2, <0.4"
pyvista = { version = ">=0.46.3, <0.47", extras = ["all"] }

